# Generated by Django 4.1.7 on 2023-03-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='pic',
            field=models.ImageField(default='ddf', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
